apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cjihie91x-python 
  janus-idp.io/tekton: cjihie91x-python
  backstage.io/kubernetes-id: cjihie91x-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cjihie91x-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  