apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cjihie91x-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cjihie91x-python 
  name: cjihie91x-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cjihie91x-python 
